name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Deploy to production
      env:
        DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        # Add your deployment script here
        # For example, using a custom deploy script:
        # ./scripts/deploy.sh
        echo "Deploying to $DEPLOY_URL"

